FROM node:6.2.2-slim

RUN mkdir -p /cwd
WORKDIR /cwd

RUN apt-get update && apt-get -y install bzip2 python && apt-get clean

COPY package.json /cwd
RUN npm install
RUN npm install -g gulp

EXPOSE 3000

CMD [ "gulp", "serve" ]
